### ISSUE TITLE
RSS feed not updating properly

### ISSUE THREAD

**Issue by codeinteger6** [irfancharania/fb-feed-gen#6]
I've been using this to get RSS feed for the [Animax Asia Facebook page](https://www.facebook.com/AnimaxAsiaTV), but it doesn't seem to be updating properly.

Earlier today a new post was made on the page, but for some reason, checking the RSS feed it shows [the latest post](https://www.facebook.com/animaxasiatv/posts/10157299535875439) was made on 9 April!

```
<title type="text">Star-cross lovers or arch enemies now? 🤔 #ZervisWoes Catch the weekend repeats of 'FAIRY TAIL Final...</title>
    <id>https://mbasic.facebook.com/story.php?story_fbid=10157299535875439&amp;id=194854365438</id>
    <updated>2019-04-09T00:00:00Z</updated>
    <published>2019-04-09T00:00:00Z</published>
    <link href="https://mbasic.facebook.com/story.php?story_fbid=10157299535875439&amp;id=194854365438" />
```

Furthermore, the update date at the top of the RSS feed shows it was last updated on 18 April. Isn't it supposed to say 20th (which is today)?

```
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title type="text">AnimaxAsiaTV FB Posts</title>
  <id>http://fbrssnews.herokuapp.com/data?username=AnimaxAsiaTV</id>
  <updated>2019-04-18T19:00:00Z</updated>
```

Due to these the RSS reader failed to retrieve the new item.

**Comment by irfancharania** [comment]
It's failing to convert the "x hours ago" into a date. 

Rather than grabbing the date from between the <abbr> tag, it'd be better to grab the published milliseconds value from the data-ft attribute and convert it.

I don't have time to fix this right now but if you want to give it a shot, I'll take a pull request.

<img width="835" alt="fbfeed_error" src="https://user-images.githubusercontent.com/3255038/56458756-6760d700-633f-11e9-9375-d719bdb0f736.png">

**Comment by codeinteger6** [comment]
I understand your busy schedule. I do hope you can fix this ASAP as I can hardly find anything else that can turn Facebook pages into RSS feeds, it would be greatly appreciated!

**Comment by irfancharania** [comment]
Should be fixed now

**Comment by codeinteger6** [comment]
Thanks!
